console.log("Starting twitter bot!");

var Twit = require('twit');

var config = require('./config');

var T = new Twit(config);

// Setting up a user stream
var stream = T.stream('user');

// Anytime someone tweets
stream.on('tweet', replyTweet);

// function that reply when a tweet event occurs
function replyTweet(eventMsg) {
    console.log('Follow event!!');
    var from = eventMsg.user.screen_name;
    var text = eventMsg.text;
    var replyto = eventMsg.in_reply_to_screen_name;

    var tweet = { status : '@'+from+' Coding is fun. Thank you for tweeting me :)\n' +
        'This is a auto-generated reply message by my Bot!'};

    if (replyto === 'TheNISHANT22'){
        T.post('statuses/update', tweet, sendTweet);
    }
}

// Anytime a follow event occur (when someone follows me! :P)
stream.on('follow', replyFollower);

// function that reply when a follow event occurs
function replyFollower(eventMsg) {
    console.log('Follow event!!');
    var name = eventMsg.source.name;
    var screenName = eventMsg.source.screen_name;

    var tweet = { status : '@'+screenName+' Thank you ' + name + ' for following me :)\n' +
        'This is a auto-generated reply message by my Bot!'};

    T.post('statuses/update', tweet, sendTweet);
}


// call  sendRandomTweet after a given interval
setInterval(sendRandomTweet, 1000*20);

// function to send tweet
function sendTweet(err, data, response) {
    if (err){
        console.log("Error: "+ err);
    } else {
        console.log("Success!");
    }
}

// function to generate a random tweet and post it with sendTweet function
function sendRandomTweet() {
    var x = Math.floor(Math.random() * 100);

    var tweet = { status : 'Random Number: '+ x +' ,generated by my Bot!!'};

    T.post('statuses/update', tweet, sendTweet);
}